config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'

  get '/users/new'
  get '/posts/new'
  get '/answers/new'

  get '/posts/:id(.:format)', to: 'posts#show'

  get '/signup',  to: 'users#new'

  resources :users
  resources :posts, only: [:create, :destroy]
  resources :answers, only: [:create, :destroy]
  resources :post_votes
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :post
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :post_id, presence: true
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :post_votes, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  def post_answers
    Answer.where("post_id = ?", id)
  end

  def post_votes_count
    PostVote.where("post_id = ?", id).sum(:vote)
  end
end

app/models/post_vote.rb
class PostVote < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :post_votes, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 50 },
                       uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  def user_posts
    Post.where("user_id = ?", id)
  end

  def feed
    Post.where.not("user_id = ?", id)
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def new
    @answer = Answer.new
  end

  def create
    @answer = current_user.answers.build(answer_params)
    @post = Post.find(answer_params[:post_id])
    if @answer.save
      flash[:success] = "Answer created!"
      redirect_to @post
    else
      @post_answers = []
      render 'static_pages/home'
    end
  end

  private

    def answer_params
      params.require(:answer).permit(:content, :post_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/post_votes_controller.rb
class PostVotesController < ApplicationController
  before_action :logged_in_user

  def create
    @post_vote = current_user.post_votes.build(post_votes_params)
    post = Post.find(post_votes_params[:post_id])
    if @post_vote.save
      flash[:success] = "Post upvoted!"
    end
    redirect_to post
  end

  def destroy
  end

  private

    def post_votes_params
      params.require(:post_vote).permit(:post_id, :vote)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def show
    @answer = Answer.new
    @post = Post.find(params[:id])

    @post_answers = @post.post_answers.paginate(page: params[:page])
    @is_post_voted = @post.post_votes.exists?(user_id: current_user.id)
  end

  def destroy
  end

  private

    def post_params
      params.require(:post).permit(:content, :title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @post  = current_user.posts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
    @answers = @user.answers
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "query.aiu"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/post_votes_helper.rb
module PostVotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<li id="answer-<%= answer.id %>">
  <span class="user"><%= link_to answer.user.username, answer.user %></span>
  <span class="content"><%= answer.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(answer.created_at) %> ago.
  </span>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>CS330 project</small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "query.aiu", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
         <li><%= link_to "Users", users_path %></li>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Account <b class="caret"></b>
           </a>
           <ul class="dropdown-menu">
             <li><%= link_to "Profile", current_user %></li>
             <li><%= link_to "Settings", '#' %></li>
             <li class="divider"></li>
             <li>
               <%= link_to "Log out", logout_path, method: :delete %>
             </li>
           </ul>
         </li>
       <% else %>
         <li><%= link_to "Log in", login_path %></li>
       <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="user"><%= link_to post.user.username, post.user %></span>
  <span class="content"><%= post.title %></span>
  <span class="content"><%= link_to "open post", post %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/posts/new.html.erb
<% provide(:title, "New post") %>

<div class="row">
  <aside class="col-md-4">
    <section class="micropost_form">
      <%= render 'shared/post_form' %>
    </section>
  </aside>
</div>

app/views/posts/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @post.title %>
      </h1>
      <p>
        <%= @post.content %>
      </p>
      <p>
        Votes: <%= @post.post_votes_count %>
      </p>
      <section class="micropost_form">
        <%= render 'shared/post_upvote_form', post_id: @post.id,
          is_voted: @is_post_voted %>
        <%= render 'shared/post_downvote_form', post_id: @post.id, 
          is_voted: @is_post_voted %>
      </section>
    </section>
    <section class="micropost_form">
      <%= render 'shared/answer_form', post_id: @post.id %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>Answers</h3>
    <%= render 'shared/answer_feed' %>
  </div>
</div>

app/views/shared/_answer_feed.html.erb
<% if @post_answers.any? %>
  <ol class="microposts">
    <%= render @post_answers %>
  </ol>
  <%= will_paginate @post_answers %>
<% end %>

app/views/shared/_answer_form.html.erb
<%= form_for(@answer) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Type your answer..." %>
    <%= f.hidden_field :post_id, :value => post_id %>
  </div>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_post_downvote_form.html.erb
<%= form_for PostVote.new do |f| %>
  <div><%= f.hidden_field :post_id, :value => post_id %></div>
  <div><%= f.hidden_field :vote, :value => -1 %></div>
  <% if is_voted %>
    <%= f.submit "Downvote", class: "btn btn-primary", disabled: true %>
  <% else %>
    <%= f.submit "Downvote", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: "Post title..." %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Post description..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_post_upvote_form.html.erb
<%= form_for PostVote.new do |f| %>
  <div><%= f.hidden_field :post_id, :value => post_id %></div>
  <div><%= f.hidden_field :vote, :value => 1 %></div>
  <% if is_voted %>
    <%= f.submit "Upvote", class: "btn btn-primary", disabled: true %>
  <% else %>
    <%= f.submit "Upvote", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.username %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
        <%= link_to "Create new post", posts_new_path %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Post Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to Query.aiu</h1>

    <h2>
      Query.aiu is a community of university students, just like you, helping each other. Join them!
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= user.username %></h1>
      <span><%= link_to "view profile", user %></span>
      <span><%= pluralize(user.posts.count, "post") %></span>
    </section>
  </aside>
</div>

app/views/users/index.html.erb
<% if @users.any? %>
  <h3>Users (<%= @users.count %>)</h3>
  <ol>
    <%= render @users %>
  </ol>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.username %>
      </h1>
      <p>
        <%= @user.email %>
      </p>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.posts.any? %>
      <h3>Posts (<%= @user.posts.count %>)</h3>
      <ol class="microposts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>
  <div class="col-md-8">
    <% if @user.answers.any? %>
      <h3>Answers (<%= @user.answers.count %>)</h3>
      <ol class="microposts">
        <%= render @answers %>
      </ol>
    <% end %>
  </div>
</div>